Update nodejs.yml

diff --git a/.github/workflows/nodejs.yml b/.github/workflows/nodejs.yml
--- a/.github/workflows/nodejs.yml
+++ b/.github/workflows/nodejs.yml
@@ -17,23 +17,23 @@ jobs:
       - name: Checkout código
         uses: actions/checkout@v4
 
-      - name: Ler, contador e salvar
-        id: contador
-        run: |
-          if [ ! -f contador.txt ]; then
-            echo "0" > contador.txt
-          fi
-          valor=$(cat contador.txt)
-          novo=$((valor + 1))
-          echo "$novo" > contador.txt
-          echo "contador=$novo" >> $GITHUB_OUTPUT
+      # - name: Ler, contador e salvar
+      #   id: contador
+      #   run: |
+      #     if [ ! -f contador.txt ]; then
+      #       echo "0" > contador.txt
+      #     fi
+      #     valor=$(cat contador.txt)
+      #     novo=$((valor + 1))
+      #     echo "$novo" > contador.txt
+      #     echo "contador=$novo" >> $GITHUB_OUTPUT
 
-      - name: Sleep antes de executar node (contador em minutos)
-        run: |
-          contador=${{ steps.contador.outputs.contador }}
-          delay_segundos=$((contador * 60))
-          echo "Aguarde $contador minutos..."
-          sleep $delay_segundos
+      # - name: Sleep antes de executar node (contador em minutos)
+      #   run: |
+      #     contador=${{ steps.contador.outputs.contador }}
+      #     delay_segundos=$((contador * 60))
+      #     echo "Aguarde $contador minutos..."
+      #     sleep $delay_segundos
 
       - name: Configurar Node.js
         uses: actions/setup-node@v4
@@ -65,17 +65,17 @@ jobs:
       - name: Executar node index.js
         run: xvfb-run --auto-servernum -- node --trace-warnings free.js
 
-      - name: Atualiza contador.txt e screen.png
+      - name: Atualiza screen.png
         run: |
           git config --global user.name "github-actions"
           git config --global user.email "actions@github.com"
-          git add contador.txt screen.png || echo "Nada para adicionar"
-          git commit -m "Atualiza contador.txt e screen.png" || echo "Nada para commitar"
+          git add screen.png || echo "Nada para adicionar"
+          git commit -m "screen.png" || echo "Nada para commitar"
           git push --quiet || echo "Falha no push, provavelmente conflito"
 
-      - name: Fazer upload da captura de tela
-        if: success() || failure()
-        uses: actions/upload-artifact@v4
-        with:
-          name: screenshot
-          path: screen.png
+      # - name: Fazer upload da captura de tela
+      #   if: success() || failure()
+      #   uses: actions/upload-artifact@v4
+      #   with:
+      #     name: screenshot
+      #     path: screen.png
